# Generated by Django 4.2.7 on 2025-06-06 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('specialization', models.CharField(choices=[('CARDIOLOGY', 'Cardiology'), ('DERMATOLOGY', 'Dermatology'), ('ENDOCRINOLOGY', 'Endocrinology'), ('GASTROENTEROLOGY', 'Gastroenterology'), ('GENERAL_PRACTICE', 'General Practice'), ('NEUROLOGY', 'Neurology'), ('ONCOLOGY', 'Oncology'), ('ORTHOPEDICS', 'Orthopedics'), ('PEDIATRICS', 'Pediatrics'), ('PSYCHIATRY', 'Psychiatry'), ('RADIOLOGY', 'Radiology'), ('SURGERY', 'Surgery'), ('UROLOGY', 'Urology')], max_length=50)),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('years_of_experience', models.PositiveIntegerField()),
                ('hospital_affiliation', models.CharField(max_length=200)),
                ('consultation_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('availability_hours', models.CharField(help_text='e.g., Mon-Fri 9AM-5PM', max_length=100)),
                ('bio', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
